# Generated by Django 6.1 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='module_code',
            field=models.CharField(blank=True, help_text='e.g., CS4001, CS5002, CU4055', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='programme',
            field=models.CharField(choices=[('BSC_COMPUTING', 'BSc (Hons) Computing'), ('BSC_NETWORKING', 'BSc (Hons) Computer Networking & IT Security'), ('BSC_MULTIMEDIA', 'BSc (Hons) Multimedia Technologies'), ('BBA', 'BBA (International Business)'), ('OTHER', 'General Campus / Non-Academic')], default='BSC_COMPUTING', max_length=50),
        ),
    ]
