# Generated by Django 6.1 on 2026-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_tradeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='e.g., Black, Blue, Red', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., S, M, L, XL (for clothing)', max_length=20),
        ),
    ]
