# Generated by Django 6.1 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_quantity_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meetup_location',
            field=models.CharField(choices=[('BLOCK_A_HALLWAY', 'Block A - Ground Floor Hallway'), ('BLOCK_B_CAFETERIA', 'Block B - Cafeteria'), ('COFFEE_STATION', 'The Coffee Station / Juice Bar'), ('LIBRARY_ENTRANCE', 'Library Entrance'), ('LECTURE_THEATRE_LOUNGE', 'Lecture Theatre Lounge')], default='BLOCK_A_HALLWAY', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='meetup_time_notes',
            field=models.CharField(blank=True, help_text='e.g., Between 12:00 PM and 1:00 PM after Lecture', max_length=255),
        ),
    ]
