# Generated by Django 6.0.6 on 2026-07-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('product_description', models.TextField()),
                ('stock', models.IntegerField(default=1)),
                ('status', models.BooleanField()),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
