# Generated by Django 6.0.6 on 2026-07-03 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_produc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produc',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
