# Generated by Django 6.0.6 on 2026-07-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_produc_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produc',
            new_name='Product',
        ),
    ]
